configfile: "config.yaml"
# config.yaml contains the sample names and paths to the fastq files. Useful for a large number of samples and for easily changing the sample names for other users, improving replicability. 

rule all:
    input:
        "plots/quals.svg"
#rule all is the final rule in the pipeline. It specifies the final output files that should be generated by the pipeline. In this case, it is a plot of the quality scores of the variants called from the sequencing data.
# used as snakemake cannot run steps with wildcards individually, and the final step must be specified.

def get_bwa_map_input_fastqs(wildcards):
    return config["samples"][wildcards.sample]
# Function returning string from the config.yaml file, specifying the samples dictionary, and outputting the path to the fastq file for the sample specified in the wildcards as a string.
rule bwa_map:
    input:
        "data/genome.fa",
        get_bwa_map_input_fastqs
        #input specifying the genome reference file and the fastq file for the sample specified in the wildcards.
    output:
        temp("mapped_reads/{sample}.bam")
        # temp() is used to indicate that the output file is an intermediate file, deleted when pipeline is done.
    params:
        rg=r"@RG\tID:{sample}\tSM:{sample}"
        # this params is used to specify the read group information for the BAM file. The read group ID and sample name are both set to the sample name specified in the wildcards.
    log:
        "logs/bwa_mem/{sample}.log"
    threads: 8
    shell:
        "(bwa mem -R '{params.rg}' -t {threads} {input} | "
        "samtools view -Sb - > {output}) 2> {log}"


rule samtools_sort:
    input:
        "mapped_reads/{sample}.bam"
    output:
        protected("sorted_reads/{sample}.bam")
        # protected() is used to write-protect the output file, preventing it from being deleted. used for a computationally expensive step.
    shell:
        "samtools sort -T sorted_reads/{wildcards.sample} "
        "-O bam {input} > {output}"

rule samtools_index:
    input:
        "sorted_reads/{sample}.bam"
    output:
        "sorted_reads/{sample}.bam.bai"
    shell:
        "samtools index {input}"

rule bcftools_call:
    input:
        fa="data/genome.fa",
        bam=expand("sorted_reads/{sample}.bam", sample=config["samples"]),
        bai=expand("sorted_reads/{sample}.bam.bai", sample=config["samples"])
    output:
        "calls/all.vcf"
    params: 
        pmr="1.1e-2"
    log:
        "logs/bcftools_call/call.log"
    shell:
        "bcftools mpileup -f {input.fa} {input.bam} | "
        "bcftools call -mv -p {params.pmr} - > {output} 2> {log}"  

rule plot_quals:
    input:
        "calls/all.vcf"
    output:
        "plots/quals.svg"
    script:
        "scripts/plot-quals.py"

